package com.hapi.coroutines_datasource

import  kotlinx.coroutines.flow.Flow
import com.hapi.datasource.BaseReposity
import com.hapi.datasource.FlowDataFetcher
import com.hapi.datasource.RxDataFetcher
import com.hapi.datasource.cache.SpCacheProvide
import com.qizhou.annotation.NetworkFetchStrategy
import io.reactivex.Observable
import java.lang.Integer
import java.util.List
import kotlin.Int

/**
 * This file is generated by kapt, please do not edit this file */
open class TestReposity : BaseReposity<TestService>() {
    suspend fun a(a: Int): in User = apiService.a(a)

    fun c(a: Int): Flow<in List<out User>> {
         return FlowDataFetcher(Ap(),NetworkFetchStrategy.OnlyRemote){
                 apiService.c(a)
                }.startFetchData()
    }

    fun d(a: Int): Observable<kotlin.collections.List<User>> {
         return RxDataFetcher(Ap(),NetworkFetchStrategy.OnlyRemote){
                 apiService.d(a)
                }.startFetchData()
    }

    fun b(a: Int): Flow<in Integer> {
         return FlowDataFetcher(SpCacheProvide("b${a}",10800000,in Integer::class.java),NetworkFetchStrategy.CacheFirst){
                 apiService.b(a)
                }.startFetchData()
    }
}
